# Generated by Django 4.0 on 2022-01-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='cantLibros',
            field=models.IntegerField(),
        ),
    ]
