# Generated by Django 4.0 on 2022-01-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0002_alter_autor_cantlibros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='libro',
            name='publicacion',
            field=models.IntegerField(),
        ),
    ]
