# Generated by Django 4.0 on 2022-01-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0004_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigocurso', models.IntegerField()),
                ('docente', models.CharField(max_length=30)),
                ('diahorario', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
