# Generated by Django 4.0 on 2022-02-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0008_post_vistas_like_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.socio'),
        ),
        migrations.AddField(
            model_name='like',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.socio'),
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.socio'),
        ),
        migrations.AddField(
            model_name='vistas',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.socio'),
        ),
    ]
