# Generated by Django 4.0 on 2022-02-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0009_comentarios_usuario_like_usuario_post_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='arreglar'),
            preserve_default=False,
        ),
    ]
