# Generated by Django 4.0 on 2022-02-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0012_alter_post_autor_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vistas',
            old_name='usuario',
            new_name='user',
        ),
    ]
