# Generated by Django 4.0 on 2022-02-10 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0013_rename_usuario_vistas_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='contenido',
            new_name='comentario',
        ),
    ]
