# Generated by Django 4.0 on 2022-02-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0015_alter_comentarios_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.CharField(default='nada', max_length=500),
            preserve_default=False,
        ),
    ]
